import * as anchor from "@coral-xyz/anchor";
import { Program, BN } from "@coral-xyz/anchor";
import { PublicKey, Keypair, SystemProgram, LAMPORTS_PER_SOL } from "@solana/web3.js";
import { expect } from "chai";

describe("BazaarX - Day 1 On-Chain Order Foundation", () => {
  // Configure the client to use the local cluster
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // Cast program to any before IDL is generated by anchor build
  const program: any = anchor.workspace.Bazaarx;

  // Keypairs for actors
  const admin = Keypair.generate();
  const buyer = Keypair.generate();
  const supplierA = Keypair.generate();
  const supplierB = Keypair.generate();
  const attacker = Keypair.generate();

  // Mint representations
  const canonicalUsdcMint = Keypair.generate();
  const fakeMint = Keypair.generate();

  // PDAs
  let configPda: PublicKey;
  let configBump: number;

  const getOrderPda = (buyerPubkey: PublicKey, orderId: BN): [PublicKey, number] => {
    return PublicKey.findProgramAddressSync(
      [
        Buffer.from("order"),
        buyerPubkey.toBuffer(),
        orderId.toArrayLike(Buffer, "le", 8),
      ],
      program.programId
    );
  };

  // Helper to fund accounts with SOL for rent and tx fees
  const airdrop = async (recipient: PublicKey, amountSol: number = 2) => {
    const sig = await provider.connection.requestAirdrop(
      recipient,
      amountSol * LAMPORTS_PER_SOL
    );
    const latestBlockHash = await provider.connection.getLatestBlockhash();
    await provider.connection.confirmTransaction({
      blockhash: latestBlockHash.blockhash,
      lastValidBlockHeight: latestBlockHash.lastValidBlockHeight,
      signature: sig,
    });
  };

  before(async () => {
    // Fund participating wallets
    await airdrop(admin.publicKey, 5);
    await airdrop(buyer.publicKey, 5);
    await airdrop(supplierA.publicKey, 5);
    await airdrop(supplierB.publicKey, 5);
    await airdrop(attacker.publicKey, 5);

    // Derive Config PDA
    [configPda, configBump] = PublicKey.findProgramAddressSync(
      [Buffer.from("config")],
      program.programId
    );
  });

  // =========================================================================
  // TEST 1 — Config initialization
  // =========================================================================
  it("Test 1: Admin successfully initializes Config PDA", async () => {
    await program.methods
      .initializeConfig(canonicalUsdcMint.publicKey)
      .accounts({
        admin: admin.publicKey,
        config: configPda,
        systemProgram: SystemProgram.programId,
      })
      .signers([admin])
      .rpc();

    const configAccount = await program.account.config.fetch(configPda);
    expect(configAccount.admin.toBase58()).to.equal(admin.publicKey.toBase58());
    expect(configAccount.usdcMint.toBase58()).to.equal(canonicalUsdcMint.publicKey.toBase58());
    expect(configAccount.bump).to.equal(configBump);
  });

  // =========================================================================
  // TEST 2 — Buyer creates valid order
  // =========================================================================
  it("Test 2: Buyer successfully creates a valid wholesale order", async () => {
    const orderId = new BN(1);
    const orderAmount = new BN(500_000_000); // 500 USDC (6 decimals)
    const [orderPda] = getOrderPda(buyer.publicKey, orderId);

    const beforeTxTime = Math.floor(Date.now() / 1000) - 2;

    await program.methods
      .createOrder(orderId, supplierA.publicKey, canonicalUsdcMint.publicKey, orderAmount)
      .accounts({
        buyer: buyer.publicKey,
        config: configPda,
        order: orderPda,
        systemProgram: SystemProgram.programId,
      })
      .signers([buyer])
      .rpc();

    const orderAccount = await program.account.order.fetch(orderPda);

    expect(orderAccount.orderId.toString()).to.equal(orderId.toString());
    expect(orderAccount.buyer.toBase58()).to.equal(buyer.publicKey.toBase58());
    expect(orderAccount.supplier.toBase58()).to.equal(supplierA.publicKey.toBase58());
    expect(orderAccount.mint.toBase58()).to.equal(canonicalUsdcMint.publicKey.toBase58());
    expect(orderAccount.amount.toString()).to.equal(orderAmount.toString());

    // Verify initial state is Created
    expect(orderAccount.state).to.have.property("created");

    // Timestamps
    expect(orderAccount.createdAt.toNumber()).to.be.gte(beforeTxTime);
    expect(orderAccount.acceptedAt.toNumber()).to.equal(0);
  });

  // =========================================================================
  // TEST 3 — Supplier accepts order
  // =========================================================================
  it("Test 3: Designated supplier successfully accepts order", async () => {
    const orderId = new BN(1);
    const [orderPda] = getOrderPda(buyer.publicKey, orderId);

    const beforeAcceptTime = Math.floor(Date.now() / 1000) - 2;

    await program.methods
      .acceptOrder()
      .accounts({
        supplier: supplierA.publicKey,
        order: orderPda,
      })
      .signers([supplierA])
      .rpc();

    const orderAccount = await program.account.order.fetch(orderPda);

    // Verify state transitioned to Accepted
    expect(orderAccount.state).to.have.property("accepted");
    expect(orderAccount.acceptedAt.toNumber()).to.be.gte(beforeAcceptTime);
  });

  // =========================================================================
  // TEST 4 — Zero amount rejection
  // =========================================================================
  it("Test 4 (Security): Rejects order creation with zero amount", async () => {
    const orderId = new BN(2);
    const [orderPda] = getOrderPda(buyer.publicKey, orderId);

    try {
      await program.methods
        .createOrder(orderId, supplierA.publicKey, canonicalUsdcMint.publicKey, new BN(0))
        .accounts({
          buyer: buyer.publicKey,
          config: configPda,
          order: orderPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([buyer])
        .rpc();
      expect.fail("Expected transaction to fail for zero amount");
    } catch (err: any) {
      expect(err.toString()).to.include("InvalidAmount");
    }
  });

  // =========================================================================
  // TEST 5 — Buyer is supplier rejection (self-dealing)
  // =========================================================================
  it("Test 5 (Security): Rejects order creation where buyer is also supplier", async () => {
    const orderId = new BN(3);
    const [orderPda] = getOrderPda(buyer.publicKey, orderId);

    try {
      await program.methods
        .createOrder(orderId, buyer.publicKey, canonicalUsdcMint.publicKey, new BN(100_000_000))
        .accounts({
          buyer: buyer.publicKey,
          config: configPda,
          order: orderPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([buyer])
        .rpc();
      expect.fail("Expected transaction to fail when buyer == supplier");
    } catch (err: any) {
      expect(err.toString()).to.include("InvalidSupplier");
    }
  });

  // =========================================================================
  // TEST 6 — Wrong/fake token mint rejection
  // =========================================================================
  it("Test 6 (Security): Rejects order creation with unapproved token mint", async () => {
    const orderId = new BN(4);
    const [orderPda] = getOrderPda(buyer.publicKey, orderId);

    try {
      await program.methods
        .createOrder(orderId, supplierA.publicKey, fakeMint.publicKey, new BN(100_000_000))
        .accounts({
          buyer: buyer.publicKey,
          config: configPda,
          order: orderPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([buyer])
        .rpc();
      expect.fail("Expected transaction to fail for non-USDC mint");
    } catch (err: any) {
      expect(err.toString()).to.include("InvalidMint");
    }
  });

  // =========================================================================
  // TEST 7 — Non-designated supplier acceptance rejection
  // =========================================================================
  it("Test 7 (Security): Rejects acceptance attempt by unauthorized supplier", async () => {
    // Create new order specifically designated for Supplier A
    const orderId = new BN(5);
    const [orderPda] = getOrderPda(buyer.publicKey, orderId);

    await program.methods
      .createOrder(orderId, supplierA.publicKey, canonicalUsdcMint.publicKey, new BN(200_000_000))
      .accounts({
        buyer: buyer.publicKey,
        config: configPda,
        order: orderPda,
        systemProgram: SystemProgram.programId,
      })
      .signers([buyer])
      .rpc();

    // Supplier B attempts to accept Supplier A's order
    try {
      await program.methods
        .acceptOrder()
        .accounts({
          supplier: supplierB.publicKey,
          order: orderPda,
        })
        .signers([supplierB])
        .rpc();
      expect.fail("Expected transaction to fail when wrong supplier accepts");
    } catch (err: any) {
      expect(err.toString()).to.include("UnauthorizedSupplier");
    }
  });

  // =========================================================================
  // TEST 8 — Buyer attempts acceptance rejection
  // =========================================================================
  it("Test 8 (Security): Rejects buyer attempting to accept their own order", async () => {
    const orderId = new BN(5);
    const [orderPda] = getOrderPda(buyer.publicKey, orderId);

    try {
      await program.methods
        .acceptOrder()
        .accounts({
          supplier: buyer.publicKey,
          order: orderPda,
        })
        .signers([buyer])
        .rpc();
      expect.fail("Expected transaction to fail when buyer attempts to accept");
    } catch (err: any) {
      expect(err.toString()).to.include("UnauthorizedSupplier");
    }
  });

  // =========================================================================
  // TEST 9 — Double acceptance rejection (Accepted -> Accepted)
  // =========================================================================
  it("Test 9 (Security): Rejects double acceptance on already accepted order", async () => {
    const orderId = new BN(5);
    const [orderPda] = getOrderPda(buyer.publicKey, orderId);

    // Supplier A accepts first time (valid)
    await program.methods
      .acceptOrder()
      .accounts({
        supplier: supplierA.publicKey,
        order: orderPda,
      })
      .signers([supplierA])
      .rpc();

    // Supplier A attempts to accept a second time (MUST FAIL)
    try {
      await program.methods
        .acceptOrder()
        .accounts({
          supplier: supplierA.publicKey,
          order: orderPda,
        })
        .signers([supplierA])
        .rpc();
      expect.fail("Expected transaction to fail on double acceptance");
    } catch (err: any) {
      expect(err.toString()).to.include("InvalidOrderState");
    }
  });

  // =========================================================================
  // TEST 10 — Invalid Order PDA rejection
  // =========================================================================
  it("Test 10 (Security): Rejects order creation with mismatched/spoofed PDA", async () => {
    const orderId = new BN(10);
    // Deliberately derive PDA for a different buyer (attacker) instead of legitimate buyer
    const [spoofedOrderPda] = getOrderPda(attacker.publicKey, orderId);

    try {
      await program.methods
        .createOrder(orderId, supplierA.publicKey, canonicalUsdcMint.publicKey, new BN(100_000_000))
        .accounts({
          buyer: buyer.publicKey,
          config: configPda,
          order: spoofedOrderPda, // Incorrect PDA seeds!
          systemProgram: SystemProgram.programId,
        })
        .signers([buyer])
        .rpc();
      expect.fail("Expected transaction to fail with invalid PDA seeds");
    } catch (err: any) {
      // Anchor seeds constraint check failure
      expect(err.toString()).to.satisfy(
        (msg: string) => msg.includes("ConstraintSeeds") || msg.includes("seeds")
      );
    }
  });
});
